services:
  backend:
    build: .
    container_name: poc_backend
    ports:
      - "8000:8000" # FastAPI uvicorn
    depends_on:
      - mysql_db  # "db" -> "mysql_db"로 수정
    environment:
      - DATABASE_HOST=mysql_db  # 컨테이너 이름과 맞춤
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root  
      - DATABASE_NAME=mydb

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./src/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # 설정 파일 추가
    ports:
      - "3306:3306"

volumes:
  db_data:
